### ISSUE TITLE
Estructura de carpetas

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/d-s1-evaluacion-intermedia-Albametnet#1]
Os vamos a insistir mucho en que os ajustéis a la estructura de archivos/carpetas que os propusimos el primer día: https://books.adalab.es/materiales-front-end-d/sprint-1.-hola-mundo/1.1.-intro-a-la-web#notas-finales-sobre-como-organizar-nuestro-proyecto

**Comment by Albametnet** [comment]
Gracias Carlos, ya esta corregido. Las tenía así porque realmente lo había entendido así y estaba convencida de que lo hacía bien. Solucionao!
